
import os
import configparser
from . import _constants


class BaseSetParameter:
    def __init__(self,
                 config_filename: str | None,
                 name: str) -> None:

        if config_filename is None:
            config_filename = _constants.DEFAULT_CONFIG_FILENAME

        if not os.path.exists(config_filename):
            raise FileNotFoundError("Required configuration file isn't found."
                                    " Configuration files can be generated by"
                                    " the `init` subcommand.")

        self._config = configparser.ConfigParser(
                            interpolation = configparser.ExtendedInterpolation()
                        )
        self._config.read(config_filename)

        if name in self._config:
            self._config = self._config[name]
        else:
            raise ValueError("The query section in the configuration"
                             " file does not exist.")

