# Configuration of HWAS run
#
# Most of these fields are occupied programmatically.  
# However, there could exist errors.  To account for
# possible errors, the config file is separated into three
# sections that users need to understand:
#
#   USER INPUT
#     These settings can not be deduced programmatically
#     with confidence and consequently is the responsibility
#     of the user to set.
#   USER CONFIRM ACCURACY 
#     These settings are likely deduced accurately, but
#     should be reviewed manually by a user.
#   COMPUTER GENERATED
#     These settings are programmatically set and should
#     not be modified by users.  They are assumptions of
#     the software that need to be maintained.
#
###########################################################
## USER INPUT
###########################################################
#
# Supported types are:
#   - float,
#   - character
#
# Supported normalization methods are:
#   - quantile_normal
#   - zscore
#
phenotype: 
  name: 
  type:
  norm:

covariates:
  - name: 
    type: 
    norm:

###########################################################
## USER CONFIRM ACCURACY
###########################################################
# 
# Example
#
# Directory strucure
#
# /path/to/raw_genotypes
#             |--- samples
#             |    |--- chr1_samps/
#             |    |    |--- samps.exclude_samples
#             |    |    
#             |    |--- chr2_samps/
#             |    |    |--- samps.exclude_samples
#             |    |
#             |    |--- ...
#             |    |
#             |    |--- chr20_samps/
#             |         |--- samps.exclude_samples
#             | 
#             |--- filtered_snps
#                 |--- chr1_imputation/
#                 |    |--- bad_snps.exclude_snps
#                 |    |--- sample_genos.bcf
#                 |    |--- sample_genos.bcf.csi
#                 |    |--- misc_non_used_files.txt
#                 |--- chr2_imputation/
#                 |    |--- bad_snps.exclude_snps
#                 |    |--- sample_genos.bcf
#                 |    |--- sample_genos.bcf.csi
#                 |    |--- misc_non_used_files.txt
#                 |
#                 |--- ...
#                 |    
#                 |
#                 |--- chr20_imputation/
#                      |--- bad_snps.exclude_snps
#                      |--- sample_genos.bcf
#                      |--- sample_genos.bcf.csi
#                      |--- misc_non_used_files.txt
#
#
# Corresponding config
#
#   genotypes:
#     dir: /path/to/raw_genotypes
#     samples:
#       dir: relative_path
#       filenames:
#         - filter_samps_chr1/annot_chr1_b.exclude_samples
#         - filter_samps_chr2/annot_chr2_b.exclude_samples
#         - ...
#         - filter_samps_chr20/annot_chr20_b.exclude_samples
#     chrom:
#       - name: chr1
#         dir: chr1_imputation
#         pos: bad_snps.exclude_snps
#         bcf: sample_genos.bcf
#         index: sample_genos.bcf.csi
#       - ...
#       - name: chr20
#         dir: chr20_imputation
#         pos: bad_snps.exclude_snps
#         bcf: sample_genos.bcf
#         index: sample_genos.bcf.csi

genotypes:
  dir:
  samples:
    dir:
    filenames:
  chrom:


###########################################################
## COMPUTER GENERATED
###########################################################
# Do not edit these settings
#
setup:
  rootdir: 
  subdirs:
    - scripts
    - preprocess_data:
      rootdir: preprocess_data
      subdirs:
        - samples
        - pos
    - postprocess_data:
        rootdir: postprocess_data
        subdirs:
          - pos
    - results:
        rootdir: results
        subdirs:
          - grms
          - lod
          - blup

trait:
  raw: 
    dir: preprocessed_data
    na_string: [NA, \N]
    sample_name_col:
  processed:
    dir: processed_data
    sample_file: samples
    covariate_file: covariates.tsv
    phenotype_file: 

