// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/hwas.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// stream_assoc_analysis
Rcpp::NumericVector stream_assoc_analysis(bconn_t bconn, const Rcpp::NumericVector& phenotypes, const Rcpp::NumericMatrix& covariates, const Rcpp::NumericMatrix& eig_vec, const Rcpp::NumericVector& eig_vals, const char* format_id);
RcppExport SEXP _hwas_stream_assoc_analysis(SEXP bconnSEXP, SEXP phenotypesSEXP, SEXP covariatesSEXP, SEXP eig_vecSEXP, SEXP eig_valsSEXP, SEXP format_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bconn_t >::type bconn(bconnSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type phenotypes(phenotypesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eig_vec(eig_vecSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type eig_vals(eig_valsSEXP);
    Rcpp::traits::input_parameter< const char* >::type format_id(format_idSEXP);
    rcpp_result_gen = Rcpp::wrap(stream_assoc_analysis(bconn, phenotypes, covariates, eig_vec, eig_vals, format_id));
    return rcpp_result_gen;
END_RCPP
}
// bread
bconn_t bread(const char* filename);
RcppExport SEXP _hwas_bread(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(bread(filename));
    return rcpp_result_gen;
END_RCPP
}
// bclose
int bclose(bconn_t bconn);
RcppExport SEXP _hwas_bclose(SEXP bconnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bconn_t >::type bconn(bconnSEXP);
    rcpp_result_gen = Rcpp::wrap(bclose(bconn));
    return rcpp_result_gen;
END_RCPP
}
// is_open
bool is_open(const bconn_t bconn);
RcppExport SEXP _hwas_is_open(SEXP bconnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const bconn_t >::type bconn(bconnSEXP);
    rcpp_result_gen = Rcpp::wrap(is_open(bconn));
    return rcpp_result_gen;
END_RCPP
}
// is_bcf
bool is_bcf(const char* filename);
RcppExport SEXP _hwas_is_bcf(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(is_bcf(filename));
    return rcpp_result_gen;
END_RCPP
}
// k_fmt
uint16_t k_fmt(bconn_t bconn, const char* id);
RcppExport SEXP _hwas_k_fmt(SEXP bconnSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bconn_t >::type bconn(bconnSEXP);
    Rcpp::traits::input_parameter< const char* >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(k_fmt(bconn, id));
    return rcpp_result_gen;
END_RCPP
}
// num_samples
uint32_t num_samples(bconn_t bconn);
RcppExport SEXP _hwas_num_samples(SEXP bconnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bconn_t >::type bconn(bconnSEXP);
    rcpp_result_gen = Rcpp::wrap(num_samples(bconn));
    return rcpp_result_gen;
END_RCPP
}
// num_positions
int64_t num_positions(bconn_t bconn);
RcppExport SEXP _hwas_num_positions(SEXP bconnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bconn_t >::type bconn(bconnSEXP);
    rcpp_result_gen = Rcpp::wrap(num_positions(bconn));
    return rcpp_result_gen;
END_RCPP
}
// sample_names
Rcpp::RObject sample_names(bconn_t bconn);
RcppExport SEXP _hwas_sample_names(SEXP bconnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bconn_t >::type bconn(bconnSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_names(bconn));
    return rcpp_result_gen;
END_RCPP
}
// subset_samples
int subset_samples(bconn_t bconn, Rcpp::Nullable<Rcpp::CharacterVector> nullable_samples);
RcppExport SEXP _hwas_subset_samples(SEXP bconnSEXP, SEXP nullable_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bconn_t >::type bconn(bconnSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type nullable_samples(nullable_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(subset_samples(bconn, nullable_samples));
    return rcpp_result_gen;
END_RCPP
}
// subset_pos_from_file
int subset_pos_from_file(bconn_t bconn, const char* filename);
RcppExport SEXP _hwas_subset_pos_from_file(SEXP bconnSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bconn_t >::type bconn(bconnSEXP);
    Rcpp::traits::input_parameter< const char* >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(subset_pos_from_file(bconn, filename));
    return rcpp_result_gen;
END_RCPP
}
// set_threads
int set_threads(bconn_t bconn, int n);
RcppExport SEXP _hwas_set_threads(SEXP bconnSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bconn_t >::type bconn(bconnSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(set_threads(bconn, n));
    return rcpp_result_gen;
END_RCPP
}
// next_record
Rcpp::Nullable<Rcpp::NumericMatrix> next_record(bconn_t bconn, const char* id);
RcppExport SEXP _hwas_next_record(SEXP bconnSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bconn_t >::type bconn(bconnSEXP);
    Rcpp::traits::input_parameter< const char* >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(next_record(bconn, id));
    return rcpp_result_gen;
END_RCPP
}
// calc_gsim
Rcpp::NumericMatrix calc_gsim(const bconn_t bconn, const char* id);
RcppExport SEXP _hwas_calc_gsim(SEXP bconnSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const bconn_t >::type bconn(bconnSEXP);
    Rcpp::traits::input_parameter< const char* >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_gsim(bconn, id));
    return rcpp_result_gen;
END_RCPP
}
// gsim_to_grm
void gsim_to_grm(Rcpp::NumericMatrix& gsim);
RcppExport SEXP _hwas_gsim_to_grm(SEXP gsimSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type gsim(gsimSEXP);
    gsim_to_grm(gsim);
    return R_NilValue;
END_RCPP
}
// pg_sim
Rcpp::NumericVector pg_sim(const Rcpp::NumericMatrix& grmatrix, const float heritability);
RcppExport SEXP _hwas_pg_sim(SEXP grmatrixSEXP, SEXP heritabilitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type grmatrix(grmatrixSEXP);
    Rcpp::traits::input_parameter< const float >::type heritability(heritabilitySEXP);
    rcpp_result_gen = Rcpp::wrap(pg_sim(grmatrix, heritability));
    return rcpp_result_gen;
END_RCPP
}
// pg_sim_qtl
Rcpp::NumericVector pg_sim_qtl(const bconn_t bconn, const Rcpp::NumericMatrix& grmatrix, const float qtl_freq, const float qtl_effect_size, const float heritability, const char* id, const int seed);
RcppExport SEXP _hwas_pg_sim_qtl(SEXP bconnSEXP, SEXP grmatrixSEXP, SEXP qtl_freqSEXP, SEXP qtl_effect_sizeSEXP, SEXP heritabilitySEXP, SEXP idSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const bconn_t >::type bconn(bconnSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type grmatrix(grmatrixSEXP);
    Rcpp::traits::input_parameter< const float >::type qtl_freq(qtl_freqSEXP);
    Rcpp::traits::input_parameter< const float >::type qtl_effect_size(qtl_effect_sizeSEXP);
    Rcpp::traits::input_parameter< const float >::type heritability(heritabilitySEXP);
    Rcpp::traits::input_parameter< const char* >::type id(idSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pg_sim_qtl(bconn, grmatrix, qtl_freq, qtl_effect_size, heritability, id, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hwas_stream_assoc_analysis", (DL_FUNC) &_hwas_stream_assoc_analysis, 6},
    {"_hwas_bread", (DL_FUNC) &_hwas_bread, 1},
    {"_hwas_bclose", (DL_FUNC) &_hwas_bclose, 1},
    {"_hwas_is_open", (DL_FUNC) &_hwas_is_open, 1},
    {"_hwas_is_bcf", (DL_FUNC) &_hwas_is_bcf, 1},
    {"_hwas_k_fmt", (DL_FUNC) &_hwas_k_fmt, 2},
    {"_hwas_num_samples", (DL_FUNC) &_hwas_num_samples, 1},
    {"_hwas_num_positions", (DL_FUNC) &_hwas_num_positions, 1},
    {"_hwas_sample_names", (DL_FUNC) &_hwas_sample_names, 1},
    {"_hwas_subset_samples", (DL_FUNC) &_hwas_subset_samples, 2},
    {"_hwas_subset_pos_from_file", (DL_FUNC) &_hwas_subset_pos_from_file, 2},
    {"_hwas_set_threads", (DL_FUNC) &_hwas_set_threads, 2},
    {"_hwas_next_record", (DL_FUNC) &_hwas_next_record, 2},
    {"_hwas_calc_gsim", (DL_FUNC) &_hwas_calc_gsim, 2},
    {"_hwas_gsim_to_grm", (DL_FUNC) &_hwas_gsim_to_grm, 1},
    {"_hwas_pg_sim", (DL_FUNC) &_hwas_pg_sim, 2},
    {"_hwas_pg_sim_qtl", (DL_FUNC) &_hwas_pg_sim_qtl, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_hwas(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
