# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit1_pg_addcovar <- function(genoprobs, pheno, addcovar, eigenvec, weights, se = FALSE, tol = 1e-12) {
    .Call('_hwas_fit1_pg_addcovar', PACKAGE = 'hwas', genoprobs, pheno, addcovar, eigenvec, weights, se, tol)
}

fit1_pg_intcovar <- function(genoprobs, pheno, addcovar, intcovar, eigenvec, weights, se = TRUE, tol = 1e-12) {
    .Call('_hwas_fit1_pg_intcovar', PACKAGE = 'hwas', genoprobs, pheno, addcovar, intcovar, eigenvec, weights, se, tol)
}

bopen <- function(filename, mode) {
    .Call('_hwas_bopen', PACKAGE = 'hwas', filename, mode)
}

bclose <- function(bid) {
    invisible(.Call('_hwas_bclose', PACKAGE = 'hwas', bid))
}

k_fmt <- function(bid, id) {
    .Call('_hwas_k_fmt', PACKAGE = 'hwas', bid, id)
}

num_samples <- function(bid) {
    .Call('_hwas_num_samples', PACKAGE = 'hwas', bid)
}

query_next <- function(bid, id) {
    .Call('_hwas_query_next', PACKAGE = 'hwas', bid, id)
}

subset_samples <- function(bid, filename) {
    .Call('_hwas_subset_samples', PACKAGE = 'hwas', bid, filename)
}

set_threads <- function(bid, n) {
    .Call('_hwas_set_threads', PACKAGE = 'hwas', bid, n)
}

calc_grm <- function(bid, id) {
    .Call('_hwas_calc_grm', PACKAGE = 'hwas', bid, id)
}

calc_rss_linreg <- function(X, Y, tol = 1e-12) {
    .Call('_hwas_calc_rss_linreg', PACKAGE = 'hwas', X, Y, tol)
}

calc_coef_linreg <- function(X, y, tol = 1e-12) {
    .Call('_hwas_calc_coef_linreg', PACKAGE = 'hwas', X, y, tol)
}

calc_coefSE_linreg <- function(X, y, tol = 1e-12) {
    .Call('_hwas_calc_coefSE_linreg', PACKAGE = 'hwas', X, y, tol)
}

calc_resid_linreg <- function(X, Y, tol = 1e-12) {
    .Call('_hwas_calc_resid_linreg', PACKAGE = 'hwas', X, Y, tol)
}

calc_resid_linreg_3d <- function(X, P, tol = 1e-12) {
    .Call('_hwas_calc_resid_linreg_3d', PACKAGE = 'hwas', X, P, tol)
}

fit_linreg <- function(X, y, se = TRUE, tol = 1e-12) {
    .Call('_hwas_fit_linreg', PACKAGE = 'hwas', X, y, se, tol)
}

fit_linreg_eigenchol <- function(X, y, se) {
    .Call('_hwas_fit_linreg_eigenchol', PACKAGE = 'hwas', X, y, se)
}

calc_coef_linreg_eigenchol <- function(X, y) {
    .Call('_hwas_calc_coef_linreg_eigenchol', PACKAGE = 'hwas', X, y)
}

calc_coefSE_linreg_eigenchol <- function(X, y) {
    .Call('_hwas_calc_coefSE_linreg_eigenchol', PACKAGE = 'hwas', X, y)
}

calc_rss_eigenchol <- function(X, y) {
    .Call('_hwas_calc_rss_eigenchol', PACKAGE = 'hwas', X, y)
}

calc_fitted_linreg_eigenchol <- function(X, y) {
    .Call('_hwas_calc_fitted_linreg_eigenchol', PACKAGE = 'hwas', X, y)
}

fit_linreg_eigenqr <- function(X, y, se, tol = 1e-12) {
    .Call('_hwas_fit_linreg_eigenqr', PACKAGE = 'hwas', X, y, se, tol)
}

calc_coef_linreg_eigenqr <- function(X, y, tol = 1e-12) {
    .Call('_hwas_calc_coef_linreg_eigenqr', PACKAGE = 'hwas', X, y, tol)
}

calc_coefSE_linreg_eigenqr <- function(X, y, tol = 1e-12) {
    .Call('_hwas_calc_coefSE_linreg_eigenqr', PACKAGE = 'hwas', X, y, tol)
}

calc_rss_eigenqr <- function(X, y, tol = 1e-12) {
    .Call('_hwas_calc_rss_eigenqr', PACKAGE = 'hwas', X, y, tol)
}

calc_fitted_linreg_eigenqr <- function(X, y, tol = 1e-12) {
    .Call('_hwas_calc_fitted_linreg_eigenqr', PACKAGE = 'hwas', X, y, tol)
}

calc_mvrss_eigenchol <- function(X, Y) {
    .Call('_hwas_calc_mvrss_eigenchol', PACKAGE = 'hwas', X, Y)
}

calc_mvrss_eigenqr <- function(X, Y, tol = 1e-12) {
    .Call('_hwas_calc_mvrss_eigenqr', PACKAGE = 'hwas', X, Y, tol)
}

calc_resid_eigenchol <- function(X, Y) {
    .Call('_hwas_calc_resid_eigenchol', PACKAGE = 'hwas', X, Y)
}

calc_resid_eigenqr <- function(X, Y, tol = 1e-12) {
    .Call('_hwas_calc_resid_eigenqr', PACKAGE = 'hwas', X, Y, tol)
}

Rcpp_eigen_decomp <- function(A) {
    .Call('_hwas_Rcpp_eigen_decomp', PACKAGE = 'hwas', A)
}

Rcpp_eigen_rotation <- function(K, y, X) {
    .Call('_hwas_Rcpp_eigen_rotation', PACKAGE = 'hwas', K, y, X)
}

Rcpp_calc_logdetXpX <- function(X) {
    .Call('_hwas_Rcpp_calc_logdetXpX', PACKAGE = 'hwas', X)
}

Rcpp_calcLL <- function(hsq, Kva, y, X, reml = TRUE, logdetXpX = NA_real_) {
    .Call('_hwas_Rcpp_calcLL', PACKAGE = 'hwas', hsq, Kva, y, X, reml, logdetXpX)
}

Rcpp_calcLL_mat <- function(hsq, Kva, Y, X, reml = TRUE, logdetXpX = NA_real_) {
    .Call('_hwas_Rcpp_calcLL_mat', PACKAGE = 'hwas', hsq, Kva, Y, X, reml, logdetXpX)
}

Rcpp_fitLMM <- function(Kva, y, X, reml = TRUE, check_boundary = TRUE, logdetXpX = NA_real_, tol = 1e-4) {
    .Call('_hwas_Rcpp_fitLMM', PACKAGE = 'hwas', Kva, y, X, reml, check_boundary, logdetXpX, tol)
}

Rcpp_fitLMM_mat <- function(Kva, Y, X, reml = TRUE, check_boundary = TRUE, logdetXpX = NA_real_, tol = 1e-4) {
    .Call('_hwas_Rcpp_fitLMM_mat', PACKAGE = 'hwas', Kva, Y, X, reml, check_boundary, logdetXpX, tol)
}

find_matching_cols <- function(mat, tol = 1e-12) {
    .Call('_hwas_find_matching_cols', PACKAGE = 'hwas', mat, tol)
}

find_lin_indep_cols <- function(mat, tol = 1e-12) {
    .Call('_hwas_find_lin_indep_cols', PACKAGE = 'hwas', mat, tol)
}

formX_intcovar <- function(probs, addcovar, intcovar, position, has_intercept = TRUE) {
    .Call('_hwas_formX_intcovar', PACKAGE = 'hwas', probs, addcovar, intcovar, position, has_intercept)
}

expand_genoprobs_intcovar <- function(probs, intcovar) {
    .Call('_hwas_expand_genoprobs_intcovar', PACKAGE = 'hwas', probs, intcovar)
}

weighted_matrix <- function(mat, weights) {
    .Call('_hwas_weighted_matrix', PACKAGE = 'hwas', mat, weights)
}

weighted_3darray <- function(array, weights) {
    .Call('_hwas_weighted_3darray', PACKAGE = 'hwas', array, weights)
}

matrix_x_matrix <- function(X, Y) {
    .Call('_hwas_matrix_x_matrix', PACKAGE = 'hwas', X, Y)
}

matrix_x_vector <- function(X, y) {
    .Call('_hwas_matrix_x_vector', PACKAGE = 'hwas', X, y)
}

matrix_x_3darray <- function(X, A) {
    .Call('_hwas_matrix_x_3darray', PACKAGE = 'hwas', X, A)
}

