# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stream_assoc_analysis <- function(bconn, phenotypes, covariates, eig_vec, eig_vals, format_id) {
    .Call('_hwas_stream_assoc_analysis', PACKAGE = 'hwas', bconn, phenotypes, covariates, eig_vec, eig_vals, format_id)
}

bread <- function(filename) {
    .Call('_hwas_bread', PACKAGE = 'hwas', filename)
}

bclose <- function(bconn) {
    .Call('_hwas_bclose', PACKAGE = 'hwas', bconn)
}

is_open <- function(bconn) {
    .Call('_hwas_is_open', PACKAGE = 'hwas', bconn)
}

is_bcf <- function(filename) {
    .Call('_hwas_is_bcf', PACKAGE = 'hwas', filename)
}

k_fmt <- function(bconn, id) {
    .Call('_hwas_k_fmt', PACKAGE = 'hwas', bconn, id)
}

num_samples <- function(bconn) {
    .Call('_hwas_num_samples', PACKAGE = 'hwas', bconn)
}

num_positions <- function(bconn) {
    .Call('_hwas_num_positions', PACKAGE = 'hwas', bconn)
}

sample_names <- function(bconn) {
    .Call('_hwas_sample_names', PACKAGE = 'hwas', bconn)
}

subset_samples <- function(bconn, nullable_samples = NULL) {
    .Call('_hwas_subset_samples', PACKAGE = 'hwas', bconn, nullable_samples)
}

subset_pos_from_file <- function(bconn, filename) {
    .Call('_hwas_subset_pos_from_file', PACKAGE = 'hwas', bconn, filename)
}

set_threads <- function(bconn, n) {
    .Call('_hwas_set_threads', PACKAGE = 'hwas', bconn, n)
}

next_record <- function(bconn, id) {
    .Call('_hwas_next_record', PACKAGE = 'hwas', bconn, id)
}

calc_gsim <- function(bconn, id) {
    .Call('_hwas_calc_gsim', PACKAGE = 'hwas', bconn, id)
}

gsim_to_grm <- function(gsim) {
    invisible(.Call('_hwas_gsim_to_grm', PACKAGE = 'hwas', gsim))
}

pg_sim <- function(grmatrix, heritability) {
    .Call('_hwas_pg_sim', PACKAGE = 'hwas', grmatrix, heritability)
}

pg_sim_qtl <- function(bconn, grmatrix, qtl_freq, qtl_effect_size, heritability, id, seed) {
    .Call('_hwas_pg_sim_qtl', PACKAGE = 'hwas', bconn, grmatrix, qtl_freq, qtl_effect_size, heritability, id, seed)
}

